#!/usr/bin/env ruby
require 'rubygems'
require 'json'
require 'yaml'
require 'coffee-script'
require 'pathname'

contents = File.readlines("./Source/Stash.coffee").join()
Dir.glob("./Source/**/*.coffee").each do |file|
  if File.basename(file) != "Stash.coffee"
    contents += IO.readlines(file).join("")
  end
end
cfile = File.new "Build/lattice-latest.coffee", "w"
cfile.write contents
afile = File.new "Build/lattice-latest.js", "w"
afile.write CoffeeScript.compile contents, :bare=>true

#FileUtils.copy("Themes/Blender/theme.css","Build/Blender")
