name: "G.UI"

exports: "gdotui.coffee"

web: ""

description: ""

license: ""

copyright: ""

authors: ""

sources:
  - "Source/Extras/Element.Extras.coffee"
  - "Source/Extras/Class.Extras.coffee"
  - "Source/GDotUI.coffee"
  - "Source/Core/Core.Abstract.coffee"
  - "Source/Core/Core.Icon.coffee"
  - "Source/Core/Core.IconGroup.coffee"
  - "Source/Core/Core.Tip.coffee"
  - "Source/Core/Core.Slider.coffee"
  - "Source/Core/Core.Button.coffee"
  - "Source/Core/Core.Picker.coffee"
  - "Source/Core/Core.Slot.coffee"
  - "Source/Core/Core.Toggler.coffee"
  - "Source/Core/Core.Textarea.coffee"
  - "Source/Core/Core.Overlay.coffee"
  - "Source/Core/Core.Tab.coffee"
  - "Source/Core/Core.Tabs.coffee"
  - "Source/Core/Core.Push.coffee"
  - "Source/Core/Core.PushGroup.coffee"
  - "Source/Data/Data.Select.coffee"
  - "Source/Data/Data.Abstract.coffee"
  - "Source/Data/Data.Text.coffee"
  - "Source/Data/Data.Number.coffee"
  - "Source/Data/Data.Color.coffee"
  - "Source/Data/Data.Date.coffee"
  - "Source/Data/Data.Time.coffee"
  - "Source/Data/Data.DateTime.coffee"
  - "Source/Data/Data.Table.coffee"
  - "Source/Data/Data.Unit.coffee"
  - "Source/Data/Data.List.coffee"
  - "Source/Dialog/Dialog.Prompt.coffee"
  - "Source/Interfaces/Interfaces.Children.coffee" 
  - "Source/Interfaces/Interfaces.Mux.coffee" 
  - "Source/Interfaces/Interfaces.Enabled.coffee"
  - "Source/Interfaces/Interfaces.Draggable.coffee"
  - "Source/Interfaces/Interfaces.Size.coffee"
  - "Source/Interfaces/Interfaces.Controls.coffee"
  - "Source/Iterable/Iterable.ListItem.coffee"
  - "Source/Iterable/Iterable.List.coffee"
  - "Source/Forms/Forms.Field.coffee"
  - "Source/Forms/Forms.Input.coffee"
  - "Source/Forms/Forms.Fieldset.coffee"
  - "Source/Forms/Forms.Form.coffee"
  - "Source/Pickers/Pickers.coffee"
  
