GDotUI={}
GDotUI.Theme={
    Global:{
        active: 'active',
        inactive: 'inactive'
    },
    Icons:{
      add:'../Themes/Chrome/images/add.png',  
      remove:'../Themes/Chrome/images/delete.png',
      edit: '../Themes/Chrome/images/pencil.png',
      handleVertical:'../Themes/Chrome/images/control_pause.png',
      handleHorizontal:''
    },
    Button:{
      'class':'button',
      defaultText: 'Button',
      defaultIcon: '../Themes/Chrome/images/pencil.png'
    },
    Float:{
        'class':'float',
        bottomHandle:'bottom',
        topHandle:'handle',
        content:'base',
        controls:'controls',
        iconOptions:{
            mode:'vertical',
            spacing:{
                x:0,
                y:5
            }
        }
    },
    Forms:{
        Field:{
            struct:{
                "dl":{
                    "dt":{
                        "label":''
                    },
                    "dd":{
                        "input":''
                    }
                }
            }
        }
    },
    Tab:{
        'class':'tab'
    },
    Tabs:{
        'class':'tabs'
    },
    css:'theme.css',
    Icon:{
      'class':'icon'
    },
    tipClass:'tip',
    Date:{
      'class':'date',
      next:'next',
      previous:'prev',
      title:'title',
      format:'%Y %B %d - %A',
      DateTime:{
        'class':'date-time',
        format:'%Y %B %d - %A %H:%M'
      },
      Time:{
        'class':'time',
        format:'%H:%M'
      },
      Slot:{
        'class':'time-slot'
      }
    },
    Slot:{
      'class':'slot'  
    },
    Number:{
        'class':'number',
        range:[-100,100],
        steps:200,
        reset: true
    },
    Picker:{
        'class':'picker',
        offset:10
    },
    List:{
      'class':'list'  
    },
    Overlay:{
      opacity:0.7,
      zindex:800,
      'class':'overlay'
    },
    ListItem:{
      'class':'list-item',
      title:'title',
      subTitle:'subtitle',
      iconOffset:2
    },
    Color:{
       sb:'sb',
       hue:'hue',
       black:'black',
       white:'white',
       color:'color',
       wrapper:'wrapper',
      'class':'color',
       format: 'hsl', //[hsl,rgb,hex]
       controls:{
          'class':'control',
          format:'format',
          colorBox:'colorBox'
       },
       slotControls:{
        'class':'slotcontrol'
       }
    },
    Slider:{
        barClass:'bar',
        knobClass:'knob',
        length: 80,
        width: 12
    }
}