Class.Mutators.DCollection=function(a){var b=this;(new Hash(a)).each(function(d,g){$splat(d).each(function(c){b.prototype[c]=function(){this[g].each(function(f){f[c].run(arguments,f)})}})})};Class.Mutators.Delegates=function(a){var b=this;(new Hash(a)).each(function(d,g){$splat(d).each(function(c){b.prototype[c]=function(){var f=this[g][c].apply(this[g],arguments);return f===this[g]?this:f}})})};Interfaces={};Core={};Data={};Iterable={};Pickers={};Selectors.Pseudo.disabled=function(){return this.hasClass("disabled")};
Class.Singleton=new Class({initialize:function(a,b){return new new Class(a)(b)}});if(GDotUI==null)GDotUI={};GDotUI.Config={tipZindex:100,floatZindex:0,cookieDuration:7E3};Interfaces.Mux=new Class({mux:function(){(new Hash(this)).each(function(a,b){b.test(/^_\$/)&&$type(a)=="function"&&a.run(null,this)}.bind(this))}});
Interfaces.Enabled=new Class({enable:function(){this.enabled=true;this.base.removeClass("disabled");this.fireEvent("enabled")},disable:function(){this.enabled=false;this.base.addClass("disabled");this.fireEvent("disabled")}});Drag.Float=new Class({Extends:Drag.Move,initialize:function(a,b){this.parent(a,b)},start:function(a){this.options.target==a.target&&this.parent(a)}});
Interfaces.Draggable=new Class({Implements:Options,options:{draggable:false},_$Draggable:function(){if(this.options.draggable){if(this.handle==null)this.handle=this.base;this.drag=new Drag.Float(this.base,{target:this.handle,handle:this.handle});this.drag.addEvent("drop",function(){this.fireEvent("dropped",this)}.bindWithEvent(this))}}});
Interfaces.Restoreable=new Class({Impelments:[Options],options:{useCookie:true,cookieID:null},_$Restoreable:function(){GDotUI.addEvent("init",this.loadPosition.bindWithEvent(this));this.addEvent("hide",function(){if($chk(this.options.cookieID))this.options.useCookie?Cookie.write(this.options.cookieID+".state","hidden",{duration:GDotUI.Config.cookieDuration}):window.localStorage.setItem(this.options.cookieID+".state","hidden")}.bindWithEvent(this));this.addEvent("dropped",this.savePosition.bindWithEvent(this))},
savePosition:function(){if($chk(this.options.cookieID)){var a=this.base.getPosition(),b=this.base.isVisible()?"visible":"hidden";if(this.options.useCookie){Cookie.write(this.options.cookieID+".x",a.x,{duration:GDotUI.Config.cookieDuration});Cookie.write(this.options.cookieID+".y",a.y,{duration:GDotUI.Config.cookieDuration});Cookie.write(this.options.cookieID+".state",b,{duration:GDotUI.Config.cookieDuration})}else{window.localStorage.setItem(this.options.cookieID+".x",a.x);window.localStorage.setItem(this.options.cookieID+
".y",a.y);window.localStorage.setItem(this.options.cookieID+".state",b)}}},loadPosition:function(){if($chk(this.options.cookieID))if(this.options.useCookie){this.base.setStyle("top",Cookie.read(this.options.cookieID+".y")+"px");this.base.setStyle("left",Cookie.read(this.options.cookieID+".x")+"px");Cookie.read(this.options.cookieID+".state")=="hidden"&&this.hide()}else{this.base.setStyle("top",window.localStorage.getItem(this.options.cookieID+".y")+"px");this.base.setStyle("left",window.localStorage.getItem(this.options.cookieID+
".x")+"px");window.localStorage.getItem(this.options.cookieID+".state")=="hidden"&&this.hide()}}});Interfaces.Controls=new Class({hide:function(){this.base.setStyle("opacity",0)},show:function(){this.base.setStyle("opacity",1)}});
Core.Abstract=new Class({Implements:[Events,Options,Interfaces.Mux],initialize:function(a){this.setOptions(a);this.base=new Element("div");this.create();fn=this.ready.bindWithEvent(this);this.base.store("fn",fn);this.base.addEventListener("DOMNodeInsertedIntoDocument",fn);this.mux()},create:function(){},ready:function(){this.base.removeEventListener("DOMNodeInsertedIntoDocument",this.base.retrieve("fn"),false);this.base.eliminate("fn")}});
Core.Icon=new Class({Extends:Core.Abstract,Implements:[Interfaces.Enabled,Interfaces.Controls],options:{image:null,text:"","class":GDotUI.Theme.iconClass},initialize:function(a){this.parent(a);this.enabled=true},create:function(){this.base.addClass(this.options["class"]);this.options.image!=null&&this.base.setStyle("background-image","url("+this.options.image+")");this.base.addEvent("click",function(){this.enabled&&this.fireEvent("invoked",this)}.bindWithEvent(this))}});
Core.IconGroup=new Class({Extends:Core.Abstract,Implements:Interfaces.Controls,options:{mode:"horizontal",spacing:{x:20,y:20},startAngle:0,radius:0,degree:360},initialize:function(a){this.parent(a);this.icons=[]},create:function(){this.base.setStyle("position","relative")},addIcon:function(a){if(this.icons.indexOf(a)==-1){this.base.grab(a.base);this.icons.push(a)}},removeIcon:function(a){if(this.icons.indexOf(a)!=-1){a.base.dispose();this.icons.push(a)}},ready:function(){y=x=0;size={x:0,y:0};if(this.options.mode==
"grid"){if(this.options.columns!=null)var a=this.icons.length/this.options.columns,b=this.options.columns;if(this.options.rows!=null){a=this.options.rows;b=Math.round(this.icons.length/this.options.rows)}this.icons.each(function(c,f){if(f%b==0){y+=f==0?0:c.base.getSize().y+this.options.spacing.y;x=0}else x+=f==0?x:c.base.getSize().x+this.options.spacing.x;c.base.setStyle("top",y);c.base.setStyle("left",x);c.base.setStyle("position","absolute")}.bind(this))}this.options.mode=="horizontal"&&this.icons.each(function(c,
f){x+=f==0?x:c.base.getSize().x+this.options.spacing.x;y+=f==0?0:this.options.spacing.y;c.base.setStyle("top",y);c.base.setStyle("left",x);c.base.setStyle("position","absolute")}.bind(this));if(this.options.mode=="vertical"){this.icons.each(function(c,f){x+=f==0?0:this.options.spacing.x;y+=f==0?y:c.base.getSize().y+this.options.spacing.y;if(c.base.getSize().x>size.x)size.x=c.base.getSize().x;size.y=y+c.base.getSize().y;c.base.setStyle("top",y);c.base.setStyle("left",x);c.base.setStyle("position",
"absolute")}.bind(this));this.size=size}if(this.options.mode=="circular"){var d=this.options.radius,g=this.options.degree/this.icons.length;this.icons.each(function(c,f){if(f==0){var h=this.options.startAngle*(Math.PI/180);x=-Math.round(d*Math.cos(h));y=Math.round(d*Math.sin(h))}else{x=-Math.round(d*Math.cos((g*f+this.options.startAngle)*(Math.PI/180)));y=Math.round(d*Math.sin((g*f+this.options.startAngle)*(Math.PI/180)))}c.base.setStyle("top",x);c.base.setStyle("left",y);c.base.setStyle("position",
"absolute")}.bind(this))}}});
Core.Tip=new Class({Extends:Core.Abstract,Binds:["enter","leave"],options:{text:"",location:{x:"left",y:"bottom"},offset:5},initialize:function(a){this.parent(a);this.create()},createTip:function(){this.base.addClass(GDotUI.Theme.tipClass);this.base.setStyle("position","absolute");this.base.setStyle("z-index",GDotUI.Config.tipZindex);this.base.set("html",this.options.text)},attach:function(a){this.attachedTo!=null&&this.detach();a.base.addEvent("mouseenter",this.enter);a.base.addEvent("mouseleave",
this.leave);this.attachedTo=a},detach:function(){item.base.removeEvent("mouseenter",this.enter);item.base.removeEvent("mouseleave",this.leave);this.attachedTo=null},enter:function(){this.attachedTo.enabled&&this.showTip()},leave:function(){this.attachedTo.enabled&&this.hideTip()},showTip:function(){var a=this.attachedTo.base.getPosition(),b=this.attachedTo.base.getSize();$(document).getElement("body").grab(this.base);var d=this.base.measure(function(){return this.getSize()});switch(this.options.location.x){case "left":this.tip.setStyle("left",
a.x+(b.x+this.options.offset));break;case "right":this.tip.setStyle("left",a.x+(b.x+this.options.offset));break;case "center":this.tip.setStyle("left",a.x-d.x/2+b.x/2);break}switch(this.options.location.y){case "top":this.tip.setStyle("top",a.y-(b.y+this.options.offset));break;case "bottom":this.tip.setStyle("top",a.y+(b.y+this.options.offset));break;case "center":this.tip.setStyle("top",a.y-d.y/2+b.y/2);break}},hideTip:function(){this.base.dispose()}});
ResetSlider=new Class({Extends:Slider,initialize:function(a,b,d){this.parent(a,b,d)},setRange:function(a){this.min=$chk(a[0])?a[0]:0;this.max=$chk(a[1])?a[1]:this.options.steps;this.range=this.max-this.min;this.steps=this.options.steps||this.full;this.stepSize=Math.abs(this.range)/this.steps;this.stepWidth=this.stepSize*this.full/Math.abs(this.range)}});
Class.Mutators.Delegates=function(a){var b=this;(new Hash(a)).each(function(d,g){$splat(d).each(function(c){b.prototype[c]=function(){var f=this[g][c].apply(this[g],arguments);return f===this[g]?this:f}})})};
Core.Slider=new Class({Extends:Core.Abstract,Implements:[Interfaces.Controls],Delegates:{slider:["set","setRange"]},options:{scrollBase:null,reset:false,mode:"vertical","class":GDotUI.Theme.Slider.barClass,knob:GDotUI.Theme.Slider.knobClass},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]);this.knob=(new Element("div")).addClass(this.options.knob);if(this.options.mode=="vertical"){this.base.setStyles({width:GDotUI.Theme.Slider.width,height:GDotUI.Theme.Slider.length});
this.knob.setStyles({width:GDotUI.Theme.Slider.width,height:GDotUI.Theme.Slider.width*2})}else{this.base.setStyles({width:GDotUI.Theme.Slider.length,height:GDotUI.Theme.Slider.width});this.knob.setStyles({width:GDotUI.Theme.Slider.width*2,height:GDotUI.Theme.Slider.width})}this.scrollBase=this.options.scrollBase;this.base.grab(this.knob)},ready:function(){if(this.options.reset){this.slider=new ResetSlider(this.base,this.knob,{mode:this.options.mode,steps:this.options.steps,range:this.options.range});
this.slider.set(0)}else this.slider=new Slider(this.base,this.knob,{mode:"vertical",steps:100});this.slider.addEvent("complete",function(a){this.fireEvent("complete",a+"")}.bindWithEvent(this));this.slider.addEvent("change",function(a){if(typeof a=="object")a=0;this.fireEvent("change",a+"");if(this.scrollBase!=null)this.scrollBase.scrollTop=(this.scrollBase.scrollHeight-this.scrollBase.getSize().y)/100*a}.bindWithEvent(this));this.parent()}});
Core.Float=new Class({Extends:Core.Abstract,Implements:[Interfaces.Draggable,Interfaces.Restoreable],Binds:["resize","mouseEnter","mouseLeave","hide"],options:{"class":GDotUI.Theme.Float["class"],overlay:false,closeable:true,resizeable:false,editable:false},initialize:function(a){this.parent(a);this.showSilder=false},ready:function(){this.loadPosition();this.base.grab(this.icons.base);this.base.grab(this.slider.base);this.icons.base.setStyle("right",-6);this.icons.base.setStyle("top",0);this.slider.base.setStyle("right",
-this.slider.base.getSize().x-6);this.slider.base.setStyle("top",this.icons.size.y);this.parent()},create:function(){this.base.addClass(this.options["class"]).setStyle("position","absolute").setPosition({x:0,y:0});this.base.toggleClass("inactive");this.content=new Element("div",{"class":GDotUI.Theme.Float.baseClass});this.handle=new Element("div",{"class":GDotUI.Theme.Float.handleClass});this.bottom=new Element("div",{"class":GDotUI.Theme.Float.bottomHandleClass});this.base.adopt(this.handle);this.base.adopt(this.content);
this.slider=new Core.Slider({scrollBase:this.content});this.slider.base.setStyle("position","absolute");this.slider.addEvent("complete",function(){this.scrolling=false}.bindWithEvent(this));this.slider.addEvent("change",function(){this.scrolling=true}.bindWithEvent(this));this.slider.hide();this.icons=new Core.IconGroup(GDotUI.Theme.Float.iconOptions);this.icons.base.setStyle("position","absolute");this.icons.base.addClass(GDotUI.Theme.Float.iconsClass);this.close=new Core.Icon({"class":GDotUI.Theme.Float.closeClass});
this.close.addEvent("invoked",function(){this.hide()}.bindWithEvent(this));this.edit=new Core.Icon({"class":GDotUI.Theme.Float.editClass});this.edit.addEvent("invoked",function(){this.contentElement!=null&&this.contentElement.toggleEdit!=null&&this.contentElement.toggleEdit();this.fireEvent("edit")}.bindWithEvent(this));this.options.closeable&&this.icons.addIcon(this.close);this.options.editable&&this.icons.addIcon(this.edit);this.icons.hide();this.scrollBase=$chk(this.options.scrollBase)?this.options.scrollBase:
this.content;this.scrollBase.setStyle("overflow","hidden");if(this.options.resizeable){this.base.grab(this.bottom);this.sizeDrag=new Drag(this.scrollBase,{handle:this.bottom,modifiers:{x:"",y:"height"}});this.sizeDrag.addEvent("drag",this.resize)}this.base.addEvent("mouseenter",this.mouseEnter);this.base.addEvent("mouseleave",this.mouseLeave)},mouseEnter:function(){this.base.toggleClass("active");this.base.toggleClass("inactive");$clear(this.iconsTimout);$clear(this.sliderTimout);this.showSlider&&
this.slider.show();this.icons.show();this.mouseisover=true},mouseLeave:function(){this.base.toggleClass("active");this.base.toggleClass("inactive");if(!this.scrolling){if(this.showSlider)this.sliderTimout=this.slider.hide.delay(200,this.slider);this.iconsTimout=this.icons.hide.delay(200,this.icons)}this.mouseisover=false},resize:function(){if(this.scrollBase.getScrollSize().y>this.scrollBase.getSize().y){if(!this.showSlider){this.showSlider=true;this.mouseisover&&this.slider.show()}}else if(this.showSlider){this.showSlider=
false;this.slider.hide()}},show:function(){if(!this.base.isVisible()){document.getElement("body").grab(this.base);if(this.options.overlay){GDotUI.Misc.Overlay.show();this.base.setStyle("z-index",801)}}},hide:function(){this.base.dispose()},toggle:function(a){this.base.isVisible()?this.hide(a):this.show(a)},setContent:function(a){this.contentElement=a;this.content.grab(a.base)},center:function(){this.base.position()}});
Core.Button=new Class({Extends:Core.Abstract,Implements:[Interfaces.Enabled,Interfaces.Controls],options:{image:"",text:"",calss:GDotUI.Theme.button["class"]},initialize:function(a){this.parent(a)},create:function(){delete this.base;this.base=new Element("button");this.base.addClass(this.options["class"]).set("text",this.options.text);this.icon=new Core.Icon({image:this.options.image});this.base.addEvent("click",function(){this.enabled&&this.fireEvent("invoked")}.bindWithEvent(this))},ready:function(){this.base.grab(this.icon.base);
this.icon.base.setStyle("float","left");this.parent()}});Element.Events.outerClick={base:"click",condition:function(a){a.stopPropagation();return false},onAdd:function(a){window.addEvent("click",a)},onRemove:function(a){window.removeEvent("click",a)}};
Core.Picker=new Class({Extends:Core.Abstract,Binds:["show","hide"],options:{"class":GDotUI.Theme.Picker["class"],offset:GDotUI.Theme.Picker.offset},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]).setStyle("position","absolute")},ready:function(){this.base.hasChild(this.contentElement.base)||this.base.grab(this.contentElement.base);winsize=window.getSize();asize=this.attachedTo.getSize();position=this.attachedTo.getPosition();size=this.base.getSize();
offset=this.options.offset;y=x="";if(position.x-size.x<0){x="right";xpos=position.x+asize.x+offset}if(position.x+size.x+asize.x>winsize.x){x="left";xpos=position.x-size.x-offset}if(!(position.x+size.x+asize.x>winsize.x)&&!(position.x-size.x<0)){x="center";xpos=position.x+asize.x/2-size.x/2}if(position.y>winsize.x/2){y="up";ypos=position.y-size.y-offset}else{y="down";ypos=x=="center"?position.y+asize.y+offset:position.y}this.base.setStyle("left",xpos);this.base.setStyle("top",ypos)},attach:function(a){a.addEvent("click",
this.show);this.contentElement.addEvent("change",function(b){this.attachedTo.set("value",b);this.attachedTo.fireEvent("change",b)}.bindWithEvent(this));this.attachedTo=a},show:function(a){document.getElement("body").grab(this.base);this.attachedTo.addClass("picking");a.stop();this.base.addEvent("outerClick",this.hide)},hide:function(){if(this.base.isVisible()){this.attachedTo.removeClass("picking");this.base.dispose()}},setContent:function(a){this.contentElement=a}});
Data.Abstract=new Class({Implements:[Events,Options],options:{},initialize:function(){this.setOptions();this.base=new Element("div");fn=this.ready.bindWithEvent(this);this.base.store("fn",fn);this.base.addEventListener("DOMNodeInsertedIntoDocument",fn);this.create()},ready:function(){this.base.removeEventListener("DOMNodeInsertedIntoDocument",this.base.retrieve("fn"),false);this.base.eliminate("fn")},create:function(){},setValue:function(){},getValue:function(){}});
Data.Text=new Class({Implements:Events,initialize:function(){this.base=new Element("div");this.text=new Element("textarea");this.base.grab(this.text);this.addEvent("show",function(){this.text.focus()}.bindWithEvent(this));this.text.addEvent("keyup",function(){this.fireEvent("change",this.text.get("value"))}.bindWithEvent(this))},setValue:function(a){this.text.set("value",a)}});
Data.Number=new Class({Extends:Data.Abstract,options:{"class":GDotUI.Theme.Number["class"]},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]);this.text=new Element("input",{type:"text"});this.text.set("value",0).setStyle("width",GDotUI.Theme.Slider.length);this.slider=new Core.Slider({reset:true,range:[-100,100],steps:200,mode:"horizontal"})},ready:function(){this.base.adopt(this.text,this.slider.base);this.slider.addEvent("complete",function(a){this.slider.setRange([a-
100,Number(a)+100]);this.slider.set(a)}.bindWithEvent(this));this.slider.addEvent("change",function(a){typeof a=="object"?this.text.set("value",0):this.text.set("value",a);this.fireEvent("change",a)}.bindWithEvent(this));this.text.addEvent("change",function(){var a=Number(this.text.get("value"));this.slider.setRange([a-100,Number(a)+100]);this.slider.set(a)}.bindWithEvent(this));this.text.addEvent("mousewheel",function(a){this.slider.set(Number(this.text.get("value"))+a.wheel)}.bindWithEvent(this));
this.parent()},setValue:function(a){this.slider.setRange([a-100,Number(a)+100]);this.slider.set(a)}});
Field=new Class({Extends:Drag.Move,Implements:[Class.Occlude,Class.Binds],Binds:["containerClicked"],options:{setOnClick:true,initialStep:false,x:[0,1,false],y:[0,1,false]},initialize:function(a,b,d){a=$(a);if(this.occlude("xy-field",a))return this.occluded;this.container=a;$defined(d)?d.container=a:d={container:a};this.setOptions(d);this.parent($(b),d);this.calculateLimit();if(!this.options.initialStep)this.options.initialStep={x:this.options.x[0],y:this.options.y[0]};this.set(this.options.initialStep)},
calculateLimit:function(){this.limit=this.parent();this.calculateStepFactor();return this.limit},calculateStepFactor:function(){this.offset={x:this.limit.x[0]+this.element.getStyle("margin-left").toInt()-this.container.offsetLeft,y:this.limit.y[0]+this.element.getStyle("margin-top").toInt()-this.container.offsetTop};var a=this.limit.x[1]-this.limit.x[0],b=this.limit.y[1]-this.limit.y[0];if(this.options.x[2]===false)this.options.x[2]=a;if(this.options.y[2]===false)this.options.y[2]=b;var d={x:(this.options.x[2]-
this.options.x[0])/this.options.x[1],y:(this.options.y[2]-this.options.y[0])/this.options.y[1]};this.stepFactor={x:a/d.x,y:b/d.y}},containerClicked:function(a){if(a.target!=this.element){a.stop();var b=this.container.getPosition();this.set(this.toSteps({x:a.page.x-b.x+this.element.getStyle("margin-left").toInt(),y:a.page.y-b.y+this.element.getStyle("margin-top").toInt()}));return a}},toSteps:function(a){a={x:(a.x-this.offset.x)/this.stepFactor.x*this.options.x[1],y:(a.y-this.offset.y)/this.stepFactor.y*
this.options.y[1]};a.x=Math.round(a.x-a.x%this.options.x[1])+this.options.x[0];a.y=Math.round(a.y-a.y%this.options.y[1])+this.options.y[0];return a},toPosition:function(a){var b={},d=this.options.y[2]-this.options.y[0]<0?Math.max:Math.min,g=this.options.y[2]-this.options.y[0]<0?Math.min:Math.max;b.x=(this.stepFactor.x*((this.options.x[2]-this.options.x[0]<0?Math.max:Math.min)((this.options.x[2]-this.options.x[0]<0?Math.min:Math.max)(a.x,this.options.x[0]),this.options.x[2])-this.options.x[0])+this.offset.x)/
this.options.x[1]+this.container.offsetLeft;b.y=(this.stepFactor.y*(d(g(a.y,this.options.y[0]),this.options.y[2])-this.options.y[0])+this.offset.y)/this.options.y[1]+this.container.offsetTop;return b},toElement:function(){return this.container},stop:function(){var a=this.get();this.fireEvent("complete",a);this.fireEvent("change",a);return this.parent(false)},drag:function(a){var b=this.get();this.fireEvent("tick",b);this.fireEvent("change",b);return this.parent(a)},set:function(a){this.element.setPosition(this.toPosition(a));
this.fireEvent("change",this.get())},get:function(){return this.toSteps(this.element.getPosition(this.container))},attach:function(){this.options.setOnClick&&this.container.addEvent("click",this.containerClicked);this.parent()},detach:function(){this.options.setOnClick&&this.container.removeEvent("click",this.containerClicked);this.parent()}});
Data.Color=new Class({Extends:Data.Abstract,options:{"class":GDotUI.Theme.Color["class"],sb:GDotUI.Theme.Color.sb,hue:GDotUI.Theme.Color.hue,wrapper:GDotUI.Theme.Color.wrapper,white:GDotUI.Theme.Color.white,black:GDotUI.Theme.Color.black},initialize:function(){this.parent()},create:function(){this.base.addClass(this.options["class"]);this.wrapper=(new Element("div")).addClass(this.options.wrapper);this.white=(new Element("div")).addClass(this.options.white);this.black=(new Element("div")).addClass(this.options.black);
this.color=(new Element("div")).addClass(this.options.sb);this.xyKnob=(new Element("div")).set("id","xyknob");this.xyKnob.setStyles({position:"absolute",top:0,left:0});this.wrapper.adopt(this.color,this.white,this.black,this.xyKnob);this.color_linear=(new Element("div")).addClass(this.options.hue);this.colorKnob=new Element("div",{id:"knob"});this.color_linear.grab(this.colorKnob);this.colorData=new Data.Color.Controls;this.base.adopt(this.wrapper,this.color_linear,this.colorData.base)},ready:function(){var a=
this.color.getSize();this.wrapper.setStyles({width:a.x,height:a.y,position:"relative","float":"left"});$$(this.white,this.black,this.color).setStyles({position:"absolute",top:0,left:0,width:"inherit",height:"inherit"});this.color_linear.setStyles({height:a.y,width:a.x/11.25,"float":"left"});this.colorKnob.setStyles({height:(a.y/11.25+8)/2.8,width:a.x/11.25+8});this.colorKnob.setStyle("left",(this.color_linear.getSize().x-this.colorKnob.getSize().x)/2);this.xy=new Field(this.black,this.xyKnob,{setOnClick:true,
x:[0,1,100],y:[0,1,100]});this.slide=new Slider(this.color_linear,this.colorKnob,{mode:"vertical",steps:360});this.slide.addEvent("change",function(b){if(typeof b=="object")b=0;this.bgColor=this.bgColor.setHue(b);this.color.setStyle("background-color",new $HSB(this.bgColor.hsb[0],100,100));this.setColor()}.bindWithEvent(this));this.xy.addEvent("tick",this.change.bindWithEvent(this));this.xy.addEvent("change",this.change.bindWithEvent(this));this.setValue(this.value?this.value:"#fff")},setValue:function(a){this.bgColor=
new Color(a);this.slide.set(this.bgColor.hsb[0]);this.xy.set({x:this.bgColor.hsb[1],y:100-this.bgColor.hsb[2]});this.saturation=this.bgColor.hsb[1];this.brightness=100-this.bgColor.hsb[2];this.hue=this.bgColor.hsb[0];this.setColor()},setColor:function(){this.finalColor=this.bgColor.setSaturation(this.saturation).setBrightness(100-this.brightness);this.colorData.setValue(this.finalColor);this.fireEvent("change",[this.colorData.hex.input.get("value")]);this.value=this.finalColor},change:function(a){this.saturation=
a.x;this.brightness=a.y;this.setColor()}});
Data.Color.Controls=new Class({Extends:Data.Abstract,options:{"class":GDotUI.Theme.Color.controls["class"],format:GDotUI.Theme.Color.controls.format,colorBox:GDotUI.Theme.Color.controls.colorBox},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]);this.left=(new Element("div")).setStyles({"float":"left"});this.red=new Data.Color.Controls.Field("R");this.green=new Data.Color.Controls.Field("G");this.blue=new Data.Color.Controls.Field("B");this.left.adopt(this.red.base,
this.green.base,this.blue.base);this.right=new Element("div");this.right.setStyles({"float":"left"});this.hue=new Data.Color.Controls.Field("H");this.saturation=new Data.Color.Controls.Field("S");this.brightness=new Data.Color.Controls.Field("B");this.right.adopt(this.hue.base,this.saturation.base,this.brightness.base);this.color=(new Element("div")).setStyles({"float":"left"}).addClass(this.options.colorBox);this.format=(new Element("div")).setStyles({"float":"left"}).addClass(this.options.format);
this.hex=new Data.Color.Controls.Field("Hex");this.rgb=new Data.Color.Controls.Field("RGB");this.hsb=new Data.Color.Controls.Field("HSL");this.format.adopt(this.hex.base,this.rgb.base,this.hsb.base);this.base.adopt(this.left,this.right,this.color,(new Element("div")).setStyle("clear","both"),this.format)},setValue:function(a){this.color.setStyle("background-color",a);this.red.input.set("value",a.rgb[0]);this.green.input.set("value",a.rgb[1]);this.blue.input.set("value",a.rgb[2]);this.rgb.input.set("value",
"rgb("+a.rgb[0]+", "+a.rgb[1]+", "+a.rgb[2]+")");this.hue.input.set("value",a.hsb[0]);this.saturation.input.set("value",a.hsb[1]);this.brightness.input.set("value",a.hsb[2]);this.hsb.input.set("value","hsl("+a.hsb[0]+", "+a.hsb[1]+"%, "+a.hsb[2]+"%)");this.hex.input.set("value","#"+a.hex.slice(1,7))}});
Data.Color.Controls.Field=new Class({initialize:function(a){this.base=new Element("dl");this.input=new Element("input",{type:"text",readonly:true});this.label=new Element("label",{text:a+": "});this.dt=(new Element("dt")).grab(this.label);this.dd=(new Element("dd")).grab(this.input);this.base.adopt(this.dt,this.dd)}});
Iterable.ListItem=new Class({Extends:Core.Abstract,options:{"class":GDotUI.Theme.ListItem["class"],title:"",subtitle:""},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]).setStyle("position","relative");this.remove=new Core.Icon({image:GDotUI.Theme.Icons.remove});this.handle=new Core.Icon({image:GDotUI.Theme.Icons.handleVertical});this.handle.base.addClass("list-handle");this.remove.base.setStyle("position","absolute");this.handle.base.setStyle("position",
"absolute");this.title=(new Element("div")).addClass(GDotUI.Theme.ListItem.title).set("text",this.options.title);this.subtitle=(new Element("div")).addClass(GDotUI.Theme.ListItem.subTitle).set("text",this.options.subtitle);this.base.adopt(this.title,this.subtitle);this.base.grab(this.remove.base);this.base.grab(this.handle.base);this.base.addEvent("click",function(){this.enabled&&this.fireEvent("invoked")}.bindWithEvent(this));this.base.addEvent("dblclick",function(){this.enabled&&this.editing&&this.fireEvent("edit",
this)}.bindWithEvent(this))},toggleEdit:function(){if(this.editing){this.remove.base.setStyle("right",-this.remove.base.getSize().x);this.handle.base.setStyle("left",-this.handle.base.getSize().x);this.base.setStyle("padding-left",this.base.retrieve("padding-left:old"));this.base.setStyle("padding-right",this.base.retrieve("padding-right:old"));this.editing=false}else{this.remove.base.setStyle("right",GDotUI.Theme.ListItem.iconOffset);this.handle.base.setStyle("left",GDotUI.Theme.ListItem.iconOffset);
this.base.store("padding-left:old",this.base.getStyle("padding-left"));this.base.store("padding-right:old",this.base.getStyle("padding-left"));this.base.setStyle("padding-left",Number(this.base.getStyle("padding-left").slice(0,-2))+this.handle.base.getSize().x);this.base.setStyle("padding-right",Number(this.base.getStyle("padding-right").slice(0,-2))+this.remove.base.getSize().x);this.editing=true}},ready:function(){if(!this.editing){var a=this.handle.base.getSize(),b=this.remove.base.getSize(),d=
this.base.getSize();this.remove.base.setStyles({right:-b.x,top:(d.y-b.y)/2});this.handle.base.setStyles({left:-a.x,top:(d.y-a.y)/2});this.parent()}}});
Iterable.List=new Class({Extends:Core.Abstract,options:{"class":GDotUI.Theme.List["class"]},initialize:function(a){this.parent(a)},create:function(){this.base.addClass(this.options["class"]);this.sortable=new Sortables(null,{handle:".list-handle"});this.editing=false;this.items=[]},removeItem:function(a){a.removeEvents("invoked","edit","delete");a.base.destroy();delete a},removeAll:function(){this.items.each(function(a){this.removeItem(a);delete a}.bind(this));delete this.items;this.items=[]},toggleEdit:function(){var a=
this.items.map(function(b){return b.base});if(this.editing){this.sortable.removeItems(a);this.items.each(function(b){b.toggleEdit()});this.editing=false}else{this.sortable.addItems(a);this.items.each(function(b){b.toggleEdit()});this.editing=true}},addItem:function(a){this.items.push(a);this.base.grab(a.base);a.addEvent("invoked",function(b){this.fireEvent("invoked",[b,e])}.bindWithEvent(this));a.addEvent("edit",function(){this.fireEvent("edit",arguments)}.bindWithEvent(this));a.addEvent("delete",
function(){this.fireEvent("delete",arguments)}.bindWithEvent(this))}});Pickers.Base=new Class({Implements:Options,Delegates:{picker:["attach","detach"]},options:{type:""},initialize:function(a){this.setOptions(a);this.picker=new Core.Picker;this.data=new Data[this.options.type];this.picker.setContent(this.data)}});Pickers.Color=new Pickers.Base({type:"Color"});Pickers.Number=new Pickers.Base({type:"Number"});Pickers.Text=new Pickers.Base({type:"Text"});