GDotUI.Theme={
    css:'theme.css',
    iconClass:'icon',
    tipClass:'tip',
    button:{
      'class':'button',
      width: 200
    },
    Float:{
        'class':'float',
        bottomHandleClass:'bottom',
        handleClass:'handle',
        closeClass:'close',
        baseClass:'base',
        editClass:'edit',
        iconsClass:'controls',
        iconOptions:{
            mode:'vertical',
            spacing:{
                x:0,
                y:3
            }
        }
    },
    ListItem:{
      'class':'list-item',
      title:'title',
      subTitle:'subtitle'
    },
    Icons:{
      remove:'../Themes/Blank/images/delete.png',
      handleVertical:'../Themes/Blank/images/control_pause.png',
      handleHorizontal:''
    },
    Color:{
      width:300,
      height:300,
      'class':'color'
    },
    Slider:{
        barClass:'bar',
        knobClass:'knob',
        length: 80,
        width: 12
    }
}